### Create User
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Aldi",
    "email": "aldi@gmail.com",
    "password": "12345",
    "confPassword": "12345",
    "role": "admin"
}

### get All Users
GET http://localhost:5000/users

### get Single User
GET http://localhost:5000/users/0684c6e2-7ffa-418d-9204-398f4c685474

### Update User
PATCH  http://localhost:5000/users/0684c6e2-7ffa-418d-9204-398f4c685474
Content-Type: application/json

{
    "name": "Hilda Updated",
    "email": "hilda@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "user"
}

### Delete User
DELETE   http://localhost:5000/users/0539e8d3-6ab2-41c0-9b4f-bc0b588c38d2

### Login User
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "hilda@gmail.com",
    "password": "12345"
}

### Login Admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "aldi@gmail.com",
    "password": "12345"
}

### Me
GET  http://localhost:5000/me

### Logout User
DELETE   http://localhost:5000/logout

### Get All Products
GET  http://localhost:5000/products

### Get Single Product
GET  http://localhost:5000/products/b5a2fd63-e5bd-489a-9d31-3cc010f5a30d

### POST Data Product
POST  http://localhost:5000/products
Content-Type: application/json

{
    "name" : "Product 6",
    "price" : 6000
}

### UPDATE Data Product
PATCH   http://localhost:5000/products/b5a2fd63-e5bd-489a-9d31-3cc010f5a30d
Content-Type: application/json

{
    "name" : "Product Updated",
    "price" : 7000
}

